version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-extras --only=main,docs

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

formats: all
