version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode copy

mkdocs:
  configuration: mkdocs.yml
