name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test: Python 3.8"
            python: "3.8"
            tox: py38
          - name: "Test: Python 3.9"
            python: "3.9"
            tox: py39
          - name: "Test: Python 3.10"
            python: "3.10"
            tox: py310
          - name: "Test: Python 3.11"
            python: "3.11"
            tox: py311
          - name: "Test: Python 3.12"
            python: "3.12"
            tox: py312
            coverage: true
          - name: "Lint: mypy"
            python: "3.12"
            tox: mypy
          - name: "Lint: pyright"
            python: "3.12"
            tox: pyright
          - name: "Lint: ruff-format"
            python: "3.12"
            tox: ruff-format
          - name: "Lint: ruff-lint"
            python: "3.12"
            tox: ruff-lint
          - name: "Docs"
            python: "3.12"
            tox: docs

    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-${{ matrix.tox }}-pip-${{ hashFiles('pyproject.toml', 'tox.ini') }} }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-${{ matrix.tox }}-pip-
      - run: python -m pip install poetry==1.8.2 tox==4.16.0
      - run: python -m tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: python -m tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
