name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1

  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Docs"
            python: "3.14"
            tox: docs
          - name: "pytest (3.10)"
            python: "3.10"
            tox: "3.10"
          - name: "pytest (3.11)"
            python: "3.11"
            tox: "3.11"
          - name: "pytest (3.12)"
            python: "3.12"
            tox: "3.12"
          - name: "pytest (3.13)"
            python: "3.13"
            tox: "3.13"
          - name: "pytest (3.14)"
            python: "3.14"
            tox: "3.14"
            coverage: true
          - name: "mypy"
            python: "3.14"
            tox: mypy
          - name: "pyright"
            python: "3.14"
            tox: pyright
          - name: "ruff format"
            python: "3.14"
            tox: ruff-format
          - name: "ruff lint"
            python: "3.14"
            tox: ruff-check
          - name: "ty"
            python: "3.14"
            tox: ty
          - name: "zizmor"
            python: "3.14"
            tox: zizmor

    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python }}
      - run: uv tool install tox --with tox-uv
      - run: tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        if: ${{ matrix.coverage }}
        with:
          use_oidc: true
