name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: hynek/build-and-inspect-python-package@v2

  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "pytest (3.10)"
            python: "3.10"
            tox: "3.10"
          - name: "pytest (3.11)"
            python: "3.11"
            tox: "3.11"
          - name: "pytest (3.12)"
            python: "3.12"
            tox: "3.12"
          - name: "pytest (3.13)"
            python: "3.13"
            tox: "3.13"
            coverage: true
          - name: "pytest (3.14)"
            python: "3.14"
            tox: "3.14"
          - name: "mypy"
            python: "3.13"
            tox: mypy
          - name: "pyright"
            python: "3.13"
            tox: pyright
          - name: "ruff format"
            python: "3.13"
            tox: ruff-format
          - name: "ruff lint"
            python: "3.13"
            tox: ruff-lint
          - name: "Docs"
            python: "3.13"
            tox: docs

    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - run: uv pip install tox tox-uv
      - run: tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@v5
        if: ${{ matrix.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
