name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2

  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Docs"
            python: "3.14"
            tox: docs
          - name: "pytest (3.10)"
            python: "3.10"
            tox: "3.10"
          - name: "pytest (3.11)"
            python: "3.11"
            tox: "3.11"
          - name: "pytest (3.12)"
            python: "3.12"
            tox: "3.12"
          - name: "pytest (3.13)"
            python: "3.13"
            tox: "3.13"
          - name: "pytest (3.14)"
            python: "3.14"
            tox: "3.14"
            coverage: true
          - name: "mypy"
            python: "3.14"
            tox: mypy
          - name: "pyright"
            python: "3.14"
            tox: pyright
          - name: "ruff format"
            python: "3.14"
            tox: ruff-format
          - name: "ruff lint"
            python: "3.14"
            tox: ruff-check
          - name: "zizmor"
            python: "3.14"
            tox: zizmor

    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - run: uv pip install tox tox-uv
      - run: tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        if: ${{ matrix.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
